# example netlify.toml
[build]
  command = "# no build command"
  functions = "netlify/functions"
  publish = "site"

  ## more info on configuring this file: https://www.netlify.com/docs/netlify-toml-reference/
